server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://175.178.164.43:3306/cloud_user?useSSL=false
    username: sc-itheima
    password: Ea8mEiKnSCzMYEfX
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: cn.itbill.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itbill: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
