server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://175.178.164.43:3306/cloud_order?useSSL=false
    username: sc-itheima
    password: Ea8mEiKnSCzMYEfX
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8100
#      discovery:
#        namespace: 5be6cb0b-846f-4d4b-9c0f-3da194e25c34  # dev环境

mybatis:
  type-aliases-package: cn.itbill.order.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itbill: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url: # eureka的地址信息，本身也是也是一个微服务，是为了该服务的注册
#      defaultZone: http://127.0.0.1:10086/eureka
#ribbon:
#  eager-load:
#    enabled: true # 开启饥饿加载
#    clients:
#      - userservice

